#SPDX-License-Identifier: MIT-0
---
# handlers file for install_env_kubernetes
  - name: Reload all sysctl settings
    ansible.builtin.command: sysctl --system

  - name: Reload containerd and kubelet configs
    ansible.builtin.systemd:
      name: "{{ item }}"
      enabled: true
      state: restarted
      daemon_reload: true
    loop:
      - containerd
      - kubelet
